overrides:
  compare-func: ^2.0.0
  fast-uri: 3.1.2
  flatted: 3.4.2
  lodash: 4.18.1
  lodash-es: 4.18.1
  minimatch: 3.1.4
  picomatch: 4.0.4
  rollup: 4.59.0
  tmp: 0.2.6
  undici: 7.24.0
  vite: 7.3.2
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
strictPeerDependencies: false
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - tmp@0.2.6
